### ISSUE TITLE
Updates but no changelog

### ISSUE THREAD

**Issue by nelsonblaha** [bellini666/gnome-shell-notifications-alert#51]
Is this extension actually open-source? I got an update at extensions.gnome.org this morning but no updates here since 2016.

**Comment by bellini666** [comment]
Hi @nelsonblaha 

Yes, it is opensource! It's license is [here](https://github.com/bellini666/gnome-shell-notifications-alert/blob/master/COPYING).

I'm really forgetting to make a new release at github when I upload a new version to ego, but since this extension doesn't change much you can see the changes in the commits page.

To summarize what changed since 2016 for you:

* The addition of a blacklist/whitelist for notifications
* Compatibility with `dash-to-panel` extension
* Support to change the background color
* New translations for: `pt-BR`, `de-DE`, `nl-NL`, `cs-CZ`
* Lots of fixes, specially for new gnome-shell releases

I'll try to start making some releases with changelogs in the future!

**Comment by hossman** [comment]
what exactly do you mean by "no updates here since 2016."

Open Source != github.  Just because bellini666 uses Github to host the canonical repo for the source code doesn't mean he's under any obligation to use every possible github feature in conjunction with the project -- there have been lots of commits to the source code, issue comments & resolutions, and releases to extensions.gnome.org since 2016.

**Comment by nelsonblaha** [comment]
I was just wondering if it's still open source. Thanks for the information.
